title: = Genesys RPG Asciidoc Compilation
description: The Genesys RPG Asciidoc Compilation project is a one-stop-shop for Genesys Roleplaying Game community content based in AsciiDoc.
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - talents
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font  
