= ENCUMBRANCE RULES EXPANSION KIT
James Gilmore <james.d.gilmore@gmail.com>
:showtitle:
:page-title: Encumbrance Rules Expansion Kit
:page-description: Encumbrance Rules Expansion Kit for the Genesys Roleplaying Game
:imagesdir: images
:toc:
:imagesdir: images

include::_include-symbols.adoc[]

== Purpose of the Expansion

=== Encumbrance Is a Tradeoff

Encumrance is a finkicky thing. On the one hand, the encumbrance threshold values can be extremely arbitrary, and likewise the encumbrance value of cargo. On the other, the purpose of abstracting carrying capacity to "encumbrance" is to compress a huge amount of information down to a tiny little package that can easily be handwaved as magic so we can stop talking about mathematics and focus on role-playing. Do we just use the encumbrance rules as-is, or do we go so deep into the particulars of cargo storage that the idea of using the encumbrance rules makes no sense at all? In many cases, a handwave is all that is necessary in a narrative system.

=== But Not a Tradeoff We Are Happy About

But if you're playing a smuggler/pirate/shipping crew (and who isn't??) then the encumbrance rules as presented leave _a lot_ to be desired. There's no rhyme or reason to encumbrance as it is presented. There is no way to wrestle it into submission. It's just a game aspect that you handwave because, ultimately, that's the game designers' expectation. Everyone at the table is utterly unhappy about it, but nobody has any better ideas that don't dramatically alter the game and create _a lot of work._

== A Solution That Fits the Genesys System

But what if there's a middle ground? What if you can leave the arbitrary values in place, still leave the system more or less abstract, but still get enough crunch to fiddle with that players enjoy it and have some skin in it?

=== The Proposal

____
"Quartermaster!"

"Aye, sir?"

"Have the men store today's gains belowdeck. An' be swift about it; the gov'ner's spies be _everywhere."_
____

==== The Rule
Whenever it's meaningful to do so, have the person trying to store the goods make a Discipline roll if acting alone, or a Leadership roll, if directing the activities of others.

==== Base Task Difficulty
Starting at normal difficulty, if the cargo encumbrance is 75% of the remaining cargo capacity, then upgrade the base diffulty. If the cargo encumbrance is 90% of the remaining cargo capacity, then upgrade the base diffulty twice. Task Difficulty can be further modified for factors such as whether the cargo is crated/packaged, how heavy/bulky individual cargo units are, and how much cargo there is, according to circumstance.

==== Task Modifiers

Upgrade the Task Difficulty (as opposed to adding setback dice) when loading or unloading cargo during a dangerous situation, such as during a firefight, in response to a fire, or as part of an Underway Replenishment. Likewise, life-threateningly dangerous hazmat should also cause an Upgrade.

Add {setback} if a minimum number of deckhands are not available to do the task, and {boost} if there are twice as many as necessary (as fits the situation.)

NOTE: The assumption I use is that Challenge dice are meant to represent the possibility of *catastrophic events,* where Setback dice are meant to represent the sort of problems that might change the outcome, but by themselves not represent the possibility of catastrophy. The bellwether for whether a Setback should be added or the Difficulty should be upgraded should be in whether the complication *adds danger to the Task.*

Having the Right Tools for the Job might come into play with this roll. What constitutes The Right Tools is situational, but as a suggestion:

* Conveyor belts
* Hoists/Cranes
* Dollies and Forklifts
* PPE, such as gloves, steel-toe boots, lifting belts, hazmat suits, eye protection.

Environmental modifiers might be applied as well: 

* the weather/temperature/humidity
* the terrain might provide a bonus (inside a provisioned warehouse) or a setback die (loading cargo in the wilderness.)

==== Interpreting the Results

Reduce the time necessary to load the cargo by 10% per {success} beyond the initial {success}.

Failure indicates an unsuccessful attempt to load the cargo. Each {failure} represents one unit of time wasted. Whether that unit is minutes, days, or hours depends on the circumstances.

.Spending Advantage and Triumph
[.genesys,cols=2*,options="header"]
|===
|Cost|Option Results
|{advantage} or {triumph}|Reduce the Encumbrance cost of storing this cargo by 10%. This option may be chosen multiple times.
|===


.Spending Threat and Despair
[.genesys, cols=2*,options="header"]
|===
|Cost|Option Results
|{threat} or {despair}|Increase the Encumbrance cost of storing this cargo by 10%. This option may be chosen multiple times.
|{threat}{threat} or {despair}|Damage one tool used in the action by one step.
|{threat}{threat}{threat} or {despair} | Destroy one tool used in the action.
|{threat}{threat}{threat} or {despair} | A critical injury occurs to one of the workers. (If the worker is a minion, this results in a death.)
|===
