= Genesys Modern
:showtitle:
:page-title: Genesys Modern Kit
:page-description: Genesys Modern Kit
:toc:
:imagesdir: images

include::_include-symbols.adoc[]

== Purpose

This provides some equipment for modern era Genesys settings.

== Equipment

.ARMOR
[.genesys, cols="3,1,1,1,1,1",options="header"]
|===
| NAME | DEFENSE | SOAK | ENCUMBRANCE | PRICE | RARITY 

| Sackcloth | 0 | 1 | 1 | 1 | 1 
| Linen | 0 | 1 | 1 | 1 | 1 

|===

.WEAPONS
[.genesys, cols="4,1,1,1,1,1,1,1,3",options="header"]
|===

| NAME | SKILL | DAM | CRIT | RANGE | ENCUM | PRICE | RARITY | Special

9+| MELEE  
| Axe, Fireman's | Melee | +1 | 9 | Engaged | -- | -- | -- | --
| Hatchet | Melee | +1 | 9 | Engaged | -- | -- | -- | --
| Chainsaw | Melee | +1 | 9 | Engaged | -- | -- | -- | --
| Club | Melee | +1 | 9 | Engaged | -- | -- | -- | --
| Hammer, Sledge | Melee | +1 | 9 | Engaged | -- | -- | -- | --
| Katana | Melee | +2 | 3 | Engaged | 2 | 500 | 6 | Defensive 1
| Knife | Melee | +1 | 3 | Engaged | 1 | 60 | 0 | --
| Snap Baton | Melee | +1 | 4 | Engaged | 1 | 50 | 4 | Disorient 2
| Stake, Wooden | Melee | +1 | 9 | Engaged | -- | -- | -- | --

9+| RANGED 
| Shotgun | Ranged (Heavy) | 7 | 6 | Short | 3 | 550 | 2 | Blast 3, Knockdown
| Hunting Rifle | Ranged (Heavy) | 7 | 4 | Long | 2 | 750 | 3 | Cumbersome 2
| 9mm Pistol | Ranged (Light) | 4 | 5 | Short | 2 | 250 | 2 | 

|===

.GEAR
[.genesys, cols="3,1,1,1",options="header"]
|===
| ITEM | ENCUMBRANCE | PRICE | RARITY 

| Binoculars | 1 | 10 | 4 
| Binoculars, Night Vision | 1 | 5 | 7 
| Binoculars | 1 | 10 | 4 
| Binoculars | 1 | 10 | 4 
| Binoculars | 1 | 10 | 4 
| Binoculars | 1 | 10 | 4 



|===



== Vehicles

=== Sports Car

:silhouette: 2
:maxspeed: 5
:handling: +2
:htthreshold: 4
:ssthreshold: 8
:armor: 0
:defense: 0

include::vehicleblock.adoc[] 

*Control skill:* Driving

*Complement:* 1

*Passengers:* 1

*Consumables:* None

*Encumbrance capacity:* 8

*Price/rarity:* 50,000 - 100,000/5

*Weapons:* None

*Examples:* McLaren 650s; Porsche 911; Ferrari 488; Mercedes-Benz AMG GT; Audi R8; Chevrolet Corvette

The sportscar represents the accessory no modern gentleman/lady spy should be without; and, what no self-respecting, cashed up villain could pass up as a status symbol. The speed 5 accounts for these cars having top speeds of around 300km/h, and acceleration from 0-100km/h in around 3-4 seconds. At that kinds of speeds the damage from collision would be severe, as per the earlier table in the book.

The higher system strain represents that with their on-board computer controlled traction control, racing brakes, racing suspension, and performance engines designed to produce high revs, they can be pushed further than your average sedan. 

==== Variants

_The Grand Tourer_ - drop handling to +1, Encumberance up to 10, and Passengers: 1 (3 uncomfortably). HT is 5. Examples include: Aston Martin DB11

_Hypercar_ - Handling goes to +3, Encumberance drops to 5, and price/rarity goes to 350,000-500,000/7. System strain goes up to 10. Examples: Ferrari LaFerrari; McLaren 720s; Porsche 918; Bugatti Chiron

=== Muscle Car

:silhouette: 2
:maxspeed: 5
:handling: -2
:htthreshold: 5
:ssthreshold: 8
:armor: 0
:defense: 0

include::vehicleblock.adoc[] 

*Control skill:* Driving

*Complement:* 1

*Passengers:* 4

*Consumables:* None

*Encumbrance capacity*: 20

*Price/rarity:* 3,000 - 20,000/3

*Weapons:* None

*Examples:* Ford Mustang; Dodge Charger; Dodge Challenger; Chevrolet Camaro

The American staple of the 1960s and 70s, the muscle car took the concept of performance as understood in Europe at the time (speed, since they had very little downforce and thin tyres) and gave it mass market, blue collar appeal. The result was a chassic as gainly and maneuverable as a refridgerator powered by a rocket engine.

Using only the most antiquated brakes and suspension mechanisms, the muscle car is all about going forward quickly (sometimes, applying more torque than the wheels can handle - sup, Dodge?) and has the higher hull threshold to reflect its robust construction. Best suited to police chases through San Francisco.

=== Four-wheel drive/sports utility vehicle

:silhouette: 2
:maxspeed: 3
:handling: 0
:htthreshold: 6
:ssthreshold: 8
:armor: 0
:defense: 0

include::vehicleblock.adoc[] 

*Control skill:* Driving

*Complement:* 1

*Passengers:* 4 (6 uncomfortably)

*Consumables:* 1 week

*Encumberance capacity:* 40

*Price/rarity:* 15,000 - 25,000/3

*Weapons:* None

*Special:* When driving through any difficult terrain such as bush, jungle, or desert, apply no negative handling modifiers.

*Examples:* Land Rover Defender, Range Rover, Toyota Landcruiser

The SUV is a solid workhorse vehicle for any modern campaign as it's equipped to go offroad; it can carry a large quantity of people and goods internally and externally, and even can fit provisions for an extended period. Its top speed and average handling make it a poor choice for car chases, but its stronger than average hull and system strain reflect a sturdy build quality designed to be pushed a bit as you navigate steep inclines.

The soft-roader represents that curious phenomenon where people of means try to present themselves as weekend outdoor adventurers. The most offroading a Porsche Cayenne will do is usually the carpark at the local shops, or the driveway at the golf club, but that's ok. You're getting this for your group/players because they want to present an image of luxury and refinement, and because it can carry their drones, tactical gear, and a chilled bottle of Bollinger Grand Anee with ease.

==== Variants

Sports soft-roader - speed goes to 5, HT goes to 4, SS to 6, passengers to 4 only, consumables are none, encumberance to 30 and price/rarity to 50,000-70,000/4. Examples: Porsche Cayenne Turbo, Porsche Macan Turbo; BMW X5M. No special ability.

=== Street "Crotch Rocket" Motorcycle

:silhouette: 1
:maxspeed: 5
:handling: +1
:htthreshold: 2
:ssthreshold: 5
:armor: 0
:defense: 0

include::vehicleblock.adoc[] 

*Control skill:* Driving

*Complement:* 1

*Passengers:* 0

*Consumables:* None

*Encumberance capacity:* 5

*Price/rarity:* 2,000-8,000 /3

*Weapons:* None

*Examples:* Ducati 848 Evo; Triumph Speed Triple; Honda CBR

With no chassis canopy to protect you, the bike is a very vulnerable and exposed means of transport that nonetheless has given us exciting and iconic chases and imagery (the Bride in Kill Bill springs to mind). Affordable performance, too.

 
== NPCs
=== Minion/Rival
==== Average Joe
Average Joes come in all shapes and sizes.

:brawn: 1
:agility: 2
:intellect: 2
:cunning: 3
:willpower: 2
:presence: 3
:soakvalue: 3
:woundthreshold: 8
:meleedefense: 1
:rangeddefense: 1
include::minionrivalblock.adoc[]
*Love Me:* Minions have feelings too!

=== Nemesis
==== The Jerk That Runs the Joint

This is your Big Bad.

:brawn: 3
:agility: 5
:intellect: 3
:cunning: 4
:willpower: 3
:presence: 4
:soakvalue: 4
:woundthreshold: 12
:strainthreshold: 12
:meleedefense: 3
:rangeddefense: 2
include::nemesisblock.adoc[]
*The Big Bad Special:* A barbedwire-wrapped baseball bat. (Or whatever.)

=== Archetype/Species
Hey! Don't stereotype me!

==== Species Abilities

:brawn: 2
:agility: 2
:intellect: 2
:cunning: 2
:willpower: 2
:presence: 2
include::characteristicblock.adoc[]

* *Somthing Special:* Some special species thing here.
* *Some Other Thing:* Some other thing here.


