= Asciidoc Supplement Compilation For the Genesys Roleplaying System 
:showtitle:
:page-title: Genesys Asciidoc Tooling
:page-description: A site using AsciiDoc to generate Genesys suppliments.

Greetings, Traveller! You're here for one of two reasons:

. you want to use some of the content in this website in your Genesys game, or
. you want to get your own content added to the compilation.

Either way, we've got you covered! Read on.

== How can I use this content?

Game rules aren't copyrightable, per se. However, the wording of those rules can be. Even when copyright is involved, there's Fair Use. But we also don't want to step on Fantasy Flight Games' toes. Therefore, we're making some reasonable assumptions. 

The first is that Fantasy Flight Games is allowing the community to use whatever is posted on or linked in their forums for non-commercial use. The logic is this: if it's on their formums or linked on their forums, they are fully aware of it. They have the capacity to take down anything on their forums, and to send C&D requests to anything linked on their forums.

The second is that you are using the content for non-commercial use, unless the content is specifically listed with a license that permits otherwise. Where there is an explicit license attached to content, we will specify.

In a nutshell, we intend to honor the established (if unwritten) policies regarding community content, and to not violate copyrights. And in turn, that means as long as you do the same, everything should be golden. Until there _is_ written guidance, we're proceeding with the understanding that anything that causes community growth without impacting FFG's ability to make money from their product is highly (if implicitly) encouraged by them. This is congruent with the precedent FFG has set.

== Super! What goodies have you got?

Glad you asked! 

link:genesys-setting-conversion-etu.html[East Texas University Setting Conversion Kit]

link:genesys-kit-modern.html[Genesys Modern Kit]

link:genesys-kit-encumbrance.html[Genesys Encumbrance Expansion Kit]

== What Is This Witchcraft!? (And how do I get some of it?)

link:tools.html[This handy link] explains the "how," but here's the "why:" 

* Ease. Using this repository, everyone can add or remove content and easily create a website which contains just the elements they wish to add to their setting. Deep knowledge of web design is not a requirement; it's all text-based markup, not xml. 

* Expandability. If someone has a wiz-bang new community suppliment to add to the pile, a Pull Request can get it merged into the central repository. But even if the Pull Request gets rejected, it still exists in thier fork. It's simply a better sharing model than forum posts, all the way around.

* Ultra-portablility. Anyone can clone the website, stick it on a thumbdrive, and view it on a plane, or in the middle of the Sahara, or whereever. A copy can be placed on any webserver, anywhere.

* Durable. If Github crashes tomorrow and never returns, the entire contents of the repository still exist in every clone. The website can always be restored so long as one clone exists.